sudo: true
language: node_js
node_js:
- node
git:
  quiet: true
cache: npm
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      master: true
  # - edge: true
  #   provider: script
  #   script: npm run travis:production
  #   skip_cleanup: true
  #   on:
  #     tags: true